user:
  email:
    min_length: 10
    max_length: 255
    regex_format: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  phone:
    regex_format: !ruby/regexp /\d[0-9]\)*\z/
  name:
    max_length: 50
  password:
    min_length: 6
  gravatar:
    size: 80
  per_page: 10
  expiration_password: 2
home:
  preview_page_link: "https://startbootstrap.com/theme/grayscale/"
  contact_form_link: "https://startbootstrap.com/solution/contact-forms"
room:
  room_per_page: 3
  rating_max: 5
  image: "width:80%"
  usd: 23000
booking:
  booking_per_page: 5
day:
  day_from_now: 1
basket:
  max_basket: 3
bills:
  bill_per_page: 10
bookings:
  booking_per_page: 5
  min_total_price: 0
day:
  day_from_now: 1
  two_day_from_now: 2
  four_day_from_now: 4
content:
  max_content: 140
history:
  history_per_page: 5
stars_number_rate: 5
rate: [1,2,3,4,5]
api:
  v1:
    authen:
      exp: 24
      strftime_exp: "%m-%d-%Y %H:%M"
